### ISSUE TITLE
Esse projeto esta sendo mantido?

### ISSUE THREAD

**Issue by fsbflavio** [TBertuzzi/DanfePDF#1]
Ola, gostaria de saber se o projeto esta sendo mantido, notei que as ultimas atualizações são maio/22

Estou a procura de um gerador de Danfe, caso esse não esteja sendo mantido, farei um fork em um novo projeto.

Obrigado.

**Comment by TBertuzzi** [comment]
Sim , apenas preciso atualizar as referencias. mas estou aceitando pull request :)

**Comment by laserguimaraes** [comment]
boa tarde. comecei a utilizar o projeto e está funcionando muito bem. só estou com um pouco de dificuldade de colocar imagem pra funcionar no danfe. Qual especificação da foto? se tivesse uma funcionalidade de passar um caminho de imagem na nuvem seria perfeito.
